#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server:
#Accepts 4 parameters
# the path to the file to be transfered
# the IP of the server we want to transfer the file to
# the username scp connects with
# the path to the ssh private key that scp uses

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi