#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+ listens on port 80.
#+ Returns a page containig "Holberton School" when queried
#+ at the root with a curl GET request.
#+ Configures /redirect_me as a "301 Moved Permmantly".
#+ Includes a custom 404 page containing "Ceci n'est pas une page".
#+ Contains a custom HTTP header named X-served-By.
#+ The value of HTTP header is the hostname of the runnig server.

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html
echo "Holberton School" > /var/www/html/index.html
sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://cuberule.com/;
    }
    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart
