#!/usr/bin/env bash
# a Bash script that creates a RSA key pair with the requirements:
#+ Name of the created private key must be holberton
#+ Number of bits in the created key to be created 4096
#+ The created key must be protected by a passphrase

ssh-keygen -b 4096 -N betty -f holberton
